

CREATE VIEW VW_TOPICO_QUESTAO
AS SELECT TOP_DESCRICAO AS TOPICO, 
	QUE_ID, 
	QUE_DESCRICAO AS DESCRICAO, 
	QUE_RESPOSTA AS RESPOSTA
FROM 
	TOPICO as t
INNER JOIN QUESTAO as q
	ON t.TOP_ID = q.TOP_ID


select * from VW_TOPICO_QUESTAO

ALTER VIEW VW_TOPICO_QUESTAO
SELECT TOP_DESCRICAO AS TOPICO,
    QUE_ID AS ID,
    QUE_DESCRICAO AS DESCRICAO,
    QUE_RESPOSTA AS RESPOSTA
FROM 
    TOPICO AS t
INNER JOIN QUESTAO AS q
    ON t.TOP_ID = q.TOP_ID


DROP VIEW IF EXISTS VW_TOPICO_QUESTAO;  
GO  

